name: easy_localization_generator
description: Generates the localization keys from an online Google Sheet or a local csv file.
version: 0.3.4
# author: Rin Luu Van <rinlv.hn@gmail.com>
homepage: https://github.com/rinlv/easy_localization_generator
issue_tracker: https://github.com/rinlv/easy_localization_generator/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^3.0.0
  build_config: ^1.2.0
  source_gen: ^3.1.0
  http: ^1.2.1
  path: ^1.9.0
  csv: ^6.0.0
  intl: ^0.20.2
  analyzer: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
